### ISSUE TITLE
Implement navbar on the index.html file

### ISSUE THREAD

**Issue by llihcchill** [llihcchill/ROI-WebApp#3]

**Comment by KambliKritarth** [comment]
Hey am I up for the grab?

**Comment by llihcchill** [comment]
sure thing!

**Comment by KambliKritarth** [comment]
hey i cannot get the roi_main.py file running so please can you make the necessary changes so that i can proceed

**Comment by llihcchill** [comment]
hehe that was a super easy fix, go for it!

**Comment by KambliKritarth** [comment]
is it ok if i use bootstrap?

**Comment by llihcchill** [comment]
ooooh that looks good, yea go for it, already implemented bootstrap :)
